version: '3.8'

services:
  db:
    container_name: postgres-container
    image: postgres:15-alpine
    restart: always
    user: postgres
    env_file:
      - svc-variables.env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./internal/database/scripts/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  config-controller:
    container_name: config-controller-container
    depends_on:
      - db
    build:
      dockerfile: config-controller.Dockerfile
    env_file:
      - svc-variables.env
    restart: always
    ports:
      - "8080:8080"

volumes:
  db:
    driver: local